### ISSUE TITLE
Missing records on app.geo.ca

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#174]
When filtering search results by organization, there are several organizations that are returning no results. 

### Organizations EN

All of the following URLs are returning “No result.” except for DND which doesn’t appear to be a filter option. These are linked to from the Government of Canada page here: https://geo.ca/government-of-canada/

- [CFIA](https://app.geo.ca/?org=Canadian%20Food%20Inspection%20Agency)
-  [CIRNAC](https://app.geo.ca/?org=Crown-Indigenous%20Relations%20and%20Northern%20Affairs%20Canada)
- [DND](https://app.geo.ca/?org=Department%20OF%20National%20Defence)
- [HC](https://app.geo.ca/?org=Health%20Canada)
- [NRC](https://app.geo.ca/?org=National%20Research%20Council%20Canada)
- [PS](https://app.geo.ca/?org=Public%20Safety%20Canada)
- [VAC](https://app.geo.ca/?org=Veterans%20Affairs%20Canada)

### Organizations FR

All of the following are returning “Aucun résultat.”.

- [ACIA](https://app.geo.ca/?org=Agence%20canadienne%20d%27inspection%20des%20aliments&lang=fr)
- [ACC](https://app.geo.ca/?org=Anciens%20combattants%20Canada&lang=fr)
- [CNRC](https://app.geo.ca/?org=Conseil%20national%20de%20recherches%20Canada&lang=fr)
- [JUS](https://app.geo.ca/?org=Minist%C3%A8re%20de%20la%20Justice&lang=fr)
- [ISDE](https://app.geo.ca/org=Innovation,%20science%20et%20d%C3%A9veloppement%20%C3%A9conomique%20Canada&lang=fr)
- [RCAANC](https://app.geo.ca/?org=Relations%20Couronne-Autochtones%20et%20Affaires%20du%20Nord%20Canada&lang=fr)
- [SC](https://app.geo.ca/?org=Sant%C3%A9%20Canada&lang=fr)
- [SP](https://app.geo.ca/?org=S%C3%A9curit%C3%A9%20publique%20Canada&lang=fr)

### Maps
The following map URLs are returning blank maps for both English and French. 

- [Water Pollutants by Facility](https://app.geo.ca/map?rvKey=5bfddafa-795b-40c0-bcbf-cc0d7d94288c,334f4740-c9bd-4193-ba69-04c21443d2b6,21d4ad44-713c-41fd-b708-f66eadd369de) 
- [National Fire Database – Agency Provided Fire Perimeters](https://app.geo.ca/map?rvKey=a6070190-519c-49bf-9144-a503fcdabf1e)

**Comment by jaredkinger** [comment]
When filtering by different types I noticed the following:

[Dataset](https://app.geo.ca/?type=dataset)
English returns 6730 results. French returns 0 results

[Application](https://app.geo.ca/?type=application)
English returns 54 results, French returns 0 results

**Comment by jaredkinger** [comment]
Seeing a similar issue when filtering by themes.

[Economy](https://app.geo.ca/?theme=economy)
782 English results. 0 French results.

[Emergency](https://app.geo.ca/?theme=emergency)
93 English results. 0 French results.

[Environment](https://app.geo.ca/?theme=environment)
2071 English results. 0 French results.

[Imagery](https://app.geo.ca/?theme=imagery)
141 English results. 0 French results.

[Legal](https://app.geo.ca/?theme=legal)
123 English results. 0 French results.

[Society](https://app.geo.ca/?theme=society)
613 English results. 0 French results.

**Comment by bo-lu** [comment]
> Seeing a similar issue when filtering by themes.
> 
> [Economy](https://app.geo.ca/?theme=economy) 782 English results. 0 French results.
> 
> [Emergency](https://app.geo.ca/?theme=emergency) 93 English results. 0 French results.
> 
> [Environment](https://app.geo.ca/?theme=environment) 2071 English results. 0 French results.
> 
> [Imagery](https://app.geo.ca/?theme=imagery) 141 English results. 0 French results.
> 
> [Legal](https://app.geo.ca/?theme=legal) 123 English results. 0 French results.
> 
> [Society](https://app.geo.ca/?theme=society) 613 English results. 0 French results.

This is also affecting dev and stage. I have a fix for this issue but will require some more testing.

**Comment by bo-lu** [comment]
> When filtering search results by organization, there are several organizations that are returning no results.
> ### Organizations EN
> 
> All of the following URLs are returning “No result.” except for DND which doesn’t appear to be a filter option. These are linked to from the Government of Canada page here: https://geo.ca/government-of-canada/
> 
>     * [CFIA](https://app.geo.ca/?org=Canadian%20Food%20Inspection%20Agency)
> 
>     * [CIRNAC](https://app.geo.ca/?org=Crown-Indigenous%20Relations%20and%20Northern%20Affairs%20Canada)
> 
>     * [DND](https://app.geo.ca/?org=Department%20OF%20National%20Defence)
> 
>     * [HC](https://app.geo.ca/?org=Health%20Canada)
> 
>     * [NRC](https://app.geo.ca/?org=National%20Research%20Council%20Canada)
> 
>     * [PS](https://app.geo.ca/?org=Public%20Safety%20Canada)
> 
>     * [VAC](https://app.geo.ca/?org=Veterans%20Affairs%20Canada)
> 
> 
> ### Organizations FR
> 
> All of the following are returning “Aucun résultat.”.
> 
>     * [ACIA](https://app.geo.ca/?org=Agence%20canadienne%20d%27inspection%20des%20aliments&lang=fr)
> 
>     * [ACC](https://app.geo.ca/?org=Anciens%20combattants%20Canada&lang=fr)
> 
>     * [CNRC](https://app.geo.ca/?org=Conseil%20national%20de%20recherches%20Canada&lang=fr)
> 
>     * [JUS](https://app.geo.ca/?org=Minist%C3%A8re%20de%20la%20Justice&lang=fr)
> 
>     * [ISDE](https://app.geo.ca/org=Innovation,%20science%20et%20d%C3%A9veloppement%20%C3%A9conomique%20Canada&lang=fr)
> 
>     * [RCAANC](https://app.geo.ca/?org=Relations%20Couronne-Autochtones%20et%20Affaires%20du%20Nord%20Canada&lang=fr)
> 
>     * [SC](https://app.geo.ca/?org=Sant%C3%A9%20Canada&lang=fr)
> 
>     * [SP](https://app.geo.ca/?org=S%C3%A9curit%C3%A9%20publique%20Canada&lang=fr)

Fixed in: https://github.com/Canadian-Geospatial-Platform/app.geo.ca/commit/8b66441be23ba83c23d6b50379bd588824d932a3

**Comment by bo-lu** [comment]
> Seeing a similar issue when filtering by themes.
> 
> [Economy](https://app.geo.ca/?theme=economy) 782 English results. 0 French results.
> 
> [Emergency](https://app.geo.ca/?theme=emergency) 93 English results. 0 French results.
> 
> [Environment](https://app.geo.ca/?theme=environment) 2071 English results. 0 French results.
> 
> [Imagery](https://app.geo.ca/?theme=imagery) 141 English results. 0 French results.
> 
> [Legal](https://app.geo.ca/?theme=legal) 123 English results. 0 French results.
> 
> [Society](https://app.geo.ca/?theme=society) 613 English results. 0 French results.

This should now be fixed on dev and staging.

**Comment by jaredkinger** [comment]
I am seeing results when filtering by themes in French on dev but the issue still exists on staging.

The number of records has changed from what I posted previously. I am seeing really strange results when filtering by different themes on dev and staging. The pagination also seems to disappear randomly.

**Economy:** 469 EN records, previously 782
**Emergency:** 6882 EN records, previously 93
**Environment:** 1700 EN records, previously 2071
**Imagery:** 278 EN records, previously 141
**Legal:** 6882 EN records, previously 123 also saw this return less than 10 without pagination/number of results returned
**Society:** 3147 EN records, previously 613

The first page of results regardless of which theme I filter by seems to be the same. As an example these are the first 3 records displayed when filtering by each theme individually.

- [Seasonal Movements and Diving of Ringed Seals...](https://app-dev.geo.ca/result?id=ffff0ff4-1b21-11eb-8cca-1860247f53e3&lang=en)
- [Coral and Sponge Concentrations in the Eastern Arctic Region of Canada](https://app-dev.geo.ca/result?id=fff7604f-8963-4210-aead-8fc9cade59b7&lang=en)
- [Greenhouse Gas Emissions Register](https://app-dev.geo.ca/result?id=fff64fdd-2b42-4b65-af59-16f89e3507b6&lang=en)

I've even seen the results say 1 - 1 of 1 record but display all the same records above.

While testing the different themes on dev I was getting 6882 total records with no applied themes and then it changed to 7243 records. The numbers seems to vary even when filtering by the themes. Staging is showing 6614 total records. Production shows 7000.

When filtering by a theme should the number of returned records match the number of datasets returned by the [/analytics/11](https://canadian-geospatial-platform.github.io/geocore/docs/api-documentation/#viewAnalytics11) endpoint?

**Comment by jaredkinger** [comment]
@bo-lu I have been doing some querying in the database to see if there were records for any of the organizations that were returning zero results.

**CIRNAC**: There are several records that I believe should be attributed to CIRNAC but it looks like the featured_properties_contact is still using the older organization name of "Indigenous and Northern Affairs Canada". An example record would be [Inuit Communities Location](https://app.geo.ca/result?id=2bcf34b5-4e9a-431b-9e43-1eace6c873bd&lang=en)

Should we be updating the data to have the correct organization name or changing this filter to use the older organization name?

**DND**: geo.ca may be using the wrong name for this organization. It's using "Department of National Defence" but there are 2 records using "National Defence". Should this filter remain and we just update the link from geo.ca pointing to the filtered results?

**Comment by jaredkinger** [comment]
@bo-lu I double checked these filters and the only one I am currently seeing that is not returning results is the French Dataset filter "Jeu de données"
